# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    packageType: sdk
    version: '5.x' 
       
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: ' -r win-x64 -p:PublishSingleFile=true --self-contained false'
